[package]
name = "well-data-collector-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
calamine = { version = "0.32.0", features = ["dates"] }
chrono = "0.4.42"
eframe = "0.33.3"
rfd = "0.17.1"
rust_xlsxwriter = "0.92.3"
